from enum import Enum

INITIAL_HAND_SIZE = 7
MAXIMUM_MANA_VALUE = 4
FINAL_TURN = 4
DECK_SIZE = 60

MAXIMUM_NUMBER_OF_SEQUENCES = 100000
MULLIGAN_THRESHOLD = 0.15


class Strategy(Enum):
    FULL_EXPLORATION = 0
    HILL_CLIMBING = 1
    MULTI_HILL_CLIMBING = 2
    SINGLE = 3
    NOTHING = 4
    
STRATEGY = Strategy.HILL_CLIMBING

# for hill climbing
INITIAL_COMBINATION = [0] * (MAXIMUM_MANA_VALUE+1)
INITIAL_COMBINATION[0] = DECK_SIZE
INITIAL_COMBINATION = [25,14,12,7,2]
# for single
if STRATEGY == Strategy.SINGLE:
    INITIAL_COMBINATION = [22,13,10,5,4,2]


# for multi hill climbing
MULTI_HILL_CLIMBING_ITERATIONS = 5
DECK_MINIMUMS = [0] * (MAXIMUM_MANA_VALUE+1)
# DECK_MINIMUMS[4] = 4
# DECK_MINIMUMS[5] = 2
