from enum import Enum

INITIAL_HAND_SIZE = 4
MAXIMUM_MANA_VALUE = 3
FINAL_TURN = 3

MAXIMUM_NUMBER_OF_SEQUENCES = 10000
MULLIGAN_THRESHOLD = 0.08


class Strategy(Enum):
    FULL_EXPLORATION = 0
    HILL_CLIMBING = 1
    MULTI_HILL_CLIMBING = 2
    SINGLE = 3
    NOTHING = 4
    
STRATEGY = Strategy.SINGLE

MULTI_HILL_CLIMBING_ITERATIONS = 3


DECK_SIZE = 60
DECK_MINIMUMS = [0] * (MAXIMUM_MANA_VALUE+1)
